### ISSUE TITLE
Loss of background image, even after deleting the extension

### ISSUE THREAD

**Issue by ianonline** [natalieperna/layout-trello#12]
Hi Natalie, I installed your Trello layout extension, but have found problems. It appears to work well, but it 'blanks' the area with the cards in removing the background image. I disabled the extension and then deleted it, but still the background won't display. It only display in the small title area and in an empty footer area.

I quit and restarted Chrome (version 45), deleted my browser cache and cookies then logged into my Trello account again, but even then the background still won't display in the area where the cards are. I find however that in incognito mode, the background image does display properly, and in incognito mode I can't reinstall the extension. I can change the background, but the part of page with the cards in remains a blank solid colour. This loss of the background is definitely a result of using your plugin. The top half of the title bar with my name and avatar is also hidden

Can you help? Thank you.

**Comment by natalieperna** [comment]
Hi Ian,

I can't seem to reproduce this issue with backgrounds. Could you try disabling all other extensions in Settings *except* List Layouts for Trello, and reload the page ignoring the cache (<kbd>Ctrl</kbd>+<kbd>F5</kbd> or <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd>). Alternatively, try enabling *only* List Layouts for Trello in incognito mode, and see if the problem is reproduced.

If it still doesn't work, could you send me some screenshots, or even better, a video of how it occurs?

Natalie

**Comment by ianonline** [comment]
Hi Natalie, I have been recording screencasts for you and each time I do I find new solutions and better understanding. I identified the Beautify for Trello plugin (for which development appears to have ended two years ago) as causing the problem with not displaying the background. Your plugin seems to be working fine. I'll leave you a positive review.

One question I still have is the layouts button toggles between which layouts? It seems to be one row, one column, or the custom layout. Not knowing caused frustration. I suggest adding in the description on the Chrome Web Store what each of the layouts are, and make it clearer in the screenshot where to find the button. I hope this feedback helps.

**Comment by natalieperna** [comment]
Glad you were able to figure it out, and thank you for the suggestions! A dropdown would probably be better, just one of those things I haven't gotten around to. I'll improve the button label in the screenshots in the meantime.

**Comment by ianonline** [comment]
Natalie, I am still having problems and I made a short screencast to illustrate the problem.

https://vimeo.com/138400202/  Password: natalie

**Comment by natalieperna** [comment]
I can see the confusion, but that is the expected behaviour. The "custom" layout you've described is just a "grid" layout, that will wrap at the end of the page. There's nothing really customizable about it, except that you can change the order of the lists. If you add more lists, or you shrink your browser window horizontally, you should see the lists wrap into a grid, rather than add a horizontal scroll bar.

This CSS for the grid layout was kindly contributed by another user of the extension. The original purpose of the extension was only to toggle on/off the single column view, which is handy if you're working on a single monitor and want Trello in a split view. The grid view is more generally useful, but it doesn't offer much flexibility, and adding that kind of customizability isn't something I'm likely to add anytime in the future.
