### ISSUE TITLE
layout button quickly dissapears

### ISSUE THREAD

**Issue by ashgavs** [natalieperna/layout-trello#15]
Hey there,
I turned off all other extensions to ensure that we're not dealing with a compatibility issue, and chrome says the extension is in fact correctly installed and works with this version.

When I load my lists, I see a button appear in the top right corner (looks like the trello icon) but then it quickly disappears... so I can't reorganize my cards...

Edit: a ctrl-shift-r  refresh makes the button appear. This fix will work but isn't optimal.

Also thank you for making this awesome thing.

**Comment by natalieperna** [comment]
I had this problem in the past with page transitions within Trello using pushState, so the extension's content script wasn't necessarily loaded every time a board was opened. As best as I can tell, this is happening again because Trello is the partially loading the page with Javascript, which doesn't register as an event by the extension to "check whether we're on a board page now".

Not sure if there's an easy/reliable fix but I'll look into it.

Thanks for reporting it!

**Comment by v42net** [comment]
Natalie,
The same happens here. I'm using Chrome (latest version) on Windows 7 (with all updates). Using refresh (F5) as a workaround when starting my working day is not a big issue. Using lots of short lists this extension is rather important for me to keep a good overview of all my tasks. Thanks !!!

**Comment by atomicpower13** [comment]
Hi
I'm having the same issue.  Using up-to-date browsers, on a mac.  It keeps 'forgetting' to load the extension.  Which is a great extension BTW, I just wish it would stay loaded.

**Comment by natalieperna** [comment]
I'm considering skirting his issue entirely by making the Chrome toolbar button be the switch for controlling the layout instead of continuing to try to embed a button in the page, which seems to be unintuitive to new users and fraught with page loading issues.

Any opinions one way or the other?

**Comment by atomicpower13** [comment]
Hi Natalie, thanks for the response.  

For me it seems to be a page loading issue.  I am a new user, but I'm always looking for the button at the top right.  Sometimes its there, others it isn't.  If I refresh the page the button appears again.

If making the Chrome toolbar button the switch avoids the need for the page to be refreshed etc, then that would be a better option for me.  If there's still a need to switch it on everytime, then the functionality would not have improved.

It seems such an important feature that I cannot believe Trello do not try and adopt the feature and put it onto their site as a native function.  It was Trello that recommended it BTW.

Hope this helps

Rob

**Comment by natalieperna** [comment]
@ashgavs @v42net @atomicpower13 This issue should be no longer applicable with the most recent update, where layout toggling is now done with with the toolbar button rather than a button embedded on the Trello board page. If any of you would you be willing to test the development version of the extension before I release it, that would be great! Instructions for installing from source are available here: [INSTALL.md](https://github.com/natalieperna/layout-trello/blob/master/INSTALL.md).
